pragma Singleton

import QtQuick 2.0
import QuickFlux 1.1

KeyTable {
    id: actionTypes

    property string stateArmyBlocksInit: "stateArmyBlocksInit"
    property string stateArmyBlocksGameStart: "stateArmyBlocksGameStart"
    property string stateArmyBlocksArmyReadyOffense: "stateArmyBlocksArmyReadyOffense"
    property string stateArmyBlocksArmyReadyDefense: "stateArmyBlocksArmyReadyDefense"
    property string stateArmyBlocksPreCompactBlocks: "stateArmyBlocksPreCompactBlocks"
    property string stateArmyBlocksCompactBlocks: "stateArmyBlocksCompactBlocks"
    property string stateArmyBlocksCheckMatches: "stateArmyBlocksCheckMatches"
    property string stateArmyBlocksPreCheckMatches: "stateArmyBlocksPreCheckMatches"
    property string stateArmyBlocksPreWaitForLaunch: "stateArmyBlocksPreWaitForLaunch"
    property string stateArmyBlocksWaitForLaunch: "stateArmyBlocksWaitForLaunch"
    property string stateArmyBlocksNoMatches: "stateArmyBlocksNoMatches"
    property string stateArmyBlocksPreNoMatches: "stateArmyBlocksPreNoMatches"
    property string stateArmyBlocksLaunchMatches: "stateArmyBlocksLaunchMatches"
    property string stateArmyBlocksPreLaunchMatches: "stateArmyBlocksPreLaunchMatches"
    property string stateArmyBlocksCreateBlocks: "stateArmyBlocksCreateBlocks"
    property string stateArmyBlocksPreCreateBlocks: "stateArmyBlocksPreCreateBlocks"
    property string stateArmyBlocksSwapBlocks: "stateArmyBlocksSwapBlocks"
    property string stateArmyBlocksMoveComplete: "stateArmyBlocksMoveComplete"
    property string stateArmyBlocksTurnComplete: "stateArmyBlocksTurnComplete"
    property string stateArmyBlocksTurnStart: "stateArmyBlocksTurnStart"
    property string stateArmyBlocksMoveStart: "stateArmyBlocksMoveStart"
    property string stateArmyBlocksMoveMade: "stateArmyBlocksMoveMade"
    property string stateArmyBlocksWaitForQueue: "stateArmyBlocksWaitForQueue"
    property string stateArmyBlocksWaitForSync: "stateArmyBlocksWaitForSync"
    property string stateArmyBlocksWaitForStackSync: "stateArmyBlocksWaitForStackSync"
    property string stateArmyBlocksInitStackSync: "stateArmyBlockStartStackSync"
    property string stateArmyBlocksFinishedStackSync: "stateArmyBlocksFinishedStackSync"
    property string stateArmyBlocksWaitForMatcher: "stateArmyBlocksWaitForMatcher"
    property string stateArmyBlocksPreWaitForMatcher: "stateArmyBlocksPreWaitForMatcher"
    property string armyRoot: "armyRoot"
    property string armyBlocks: "armyBlock"
    property string block: "block"
    property string gameRoot: "gameRoot"
    property string armyBlocksCheckForMatches: "armyBlocksCheckForMatches"
    property string armyBlocksCompactBlocks: "armyBlocksCompactBlocks"
    property string armyBlocksRemoveMatching: "armyBlocksRemoveMatching"
    property string armyBlocksSwapBlocks: "armyBlocksSwapBlocks"
    property string armyBlocksCreateNewBlocks: "armyBlocksCreateNewBlocks"
    property string blockSetRow: "blockSetRow"
    property string blockSetColumn: "blockSetColumn"
    property string enqueueArmyBlocksSetLocked: "enqueueArmyBlocksSetLocked"
    property string enqueueArmyBlocksRemoveBlock: "enqueueArmyBlocksRemoveBlock"
    property string armyBlocksSetLocked: "armyBlocksSetLocked"
    property string armyBlocksRequestMovement: "armyBlocksRequestMovement"
    property string blockAnimationFinished: "blockAnimationFinished"
    property string blockBeginLaunchSequence: "blockBeginLaunchSequence"
    property string armyBlocksBatchLaunch: "armyBlocksBatchLaunch"
    property string armyBlocksCheckFinishedWithMatches: "armyBlocksCheckFinishedWithMatches"
    property string armyBlocksCheckFinishedWithNoMatches: "armyBlocksCheckFinishedWithNoMatches"
    property string armyBlocksMoveFinished: "armyBlocksMoveFinished"
    property string armyBlocksEndTurn: "armyBlocksEndTurn"
    property string armyBlocksEnableMouseArea: "armyBlocksEnableMouseArea"
    property string armyBlocksRequestLaunchTargetDataFromOpponent: "armyBlocksRequestLaunchTargetDataFromOpponent"
    property string armyBlocksProvideLaunchTargetDataToOpponent: "armyBlocksProvideLaunchTargetDataToOpponent"
    property string blockSetHealthAndPos: "blockSetHealthAndPos"
    property string blockLaunchCompleted: "blockLaunchCompleted"
    property string blockSetOpacity: "blockSetOpacity"
    property string blockSetColor: "blockSetColor"
    property string armyBlocksDetermineNextAction: "armyBlocksDetermineNextAction"
    property string gameRootRequestQueue: "gameRootRequestQueue"
    property string armyBlocksRequestQueue: "armyBlocksRequestQueue"
    property string armyBlocksProcessQueue: "armyBlocksProcessQueue"
    property string armyBlocksEnqueueConditional: "armyBlocksEnqueueConditional"
    property string armyBlocksProcessSync: "armyBlocksProcessSync"
    property string blockDeserialize: "blockDeserialize"
    property string armyBlocksWaitForSync: "armyBlocksWaitForSync"
    property string armyBlocksPostSyncFixUp: "armyBlocksPostSyncFixUp"
    property string armyBlocksBeginTurn: "armyBlocksBeginTurn"
    property string armyBlocksFixBlocks: "armyBlocksFixBlocks"
    property string armyBlocksRemoveBlock: "armyBlocksRemoveBlock"
    property string crossArmySignalTurnEnded: "crossArmySignalTurnEnded"
    property string signalBlockCreated: "signalBlockCreated"
    property string signalBlockRemoved: "signalBlockRemoved"
    property string signalBlocksSwapped: "signalBlocksSwapped"
    property string signalLauchComplete: "signalLauchComplete"
    property string queryNearbyBlockColors: "queryNearbyBlockColors"
    property string provideNearbyBlockColors: "provideNearbyBlockColors"
    property string provideSelfBlockColors: "provideSelfBlockColors"

    property string signalFromGameEngineSetBlockPosition: "signalFromGameEngineSetBlockPosition"
    property string sendToGameEngineBlockColorUpdated: "sendToGameEngineBlockColorUpdated"
    property string reportBlockTargetDataToBackEnd: "reportBlockTargetDataToBackEnd"
    property string blockFireAtTarget: "blockFireAtTarget"
}
